import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/react"
import { StoreProvider } from "./StoreProvider";
import "../styles/assets/css/main.css";
import "../styles/assets/css/noscript.css";
import DefaultTopbar from "./ui/defaulttopbar";
import TopNav from "./ui/topnav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RecipeBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
        <StoreProvider>
          <SpeedInsights></SpeedInsights>
          <Analytics></Analytics>
          <body className={inter.className}>
            <div>
              <DefaultTopbar/>
              <TopNav></TopNav>
            </div>
            {children}
          </body>
        </StoreProvider>
      </UserProvider>
    </html>
  );
}
